title:              Hernan Echeverry
email:              hdmecheverry@gmail.com
description:        Lambda Student - Meme Aficionado - Bear Enthusiast
author:             Hernan Echeverry
#baseurl:            "/startbootstrap-clean-blog-jekyll"
url:                "hernanecheverry.com"

# Social Profiles
#twitter_username:   SBootstrap
github_username:    HernanDarius
#facebook_username:  StartBootstrap
linkedin_username:   Hernan Echeverry

# Add your google-analytics ID here to activate google analytics
#google_analytics:   UA-166655238-1 # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
